import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${inter} bg-fixed bg-[url('../assets/bg2-bigger.jpg')]    bg-cover h-full w-screen max-w-full min-h-screen flex flex-col`}
      >
        <SessionProvider session={session}>
          <main className="bg-base-100/20 backdrop-blur-md flex-grow flex flex-col">
            <Navbar />
            {children}
          </main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
