import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter} bg-fixed bg-[url('../assets/bg2-normal.jpg')] lg:bg-[url('../assets/bg2-bigger.jpg')]   xl:bg-[url('../assets/bg2-bigger2.jpg')] bg-cover h-full w-screen max-w-full`}
      >
        <main className="bg-base-100/20 backdrop-blur-md">
          <Navbar />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
